targets:
  $default:
    builders:
      json_serializable:
        options:
          include_if_null: false
          explicit_to_json: true
        generate_for:
          include:
            - "**/data/**.dart"
            - "**/models/**.dart"
            - "**/states/**.dart"
      freezed:
        generate_for:
          include:
            - "**/data/**.dart"
            - "**/models/**.dart"
            - "**/states/**.dart"
      riverpod_generator:
        generate_for:
          include:
            - "**.dart"
