name: envawareness
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  connectivity_plus: ^5.0.2
  go_router: ^13.1.0

  zflutter:
    git:
      url: https://github.com/CarGuo/zflutter.git
      ref: 3f5e569ba96f4c94a5847aad96617f273d88629d
      path: zflutter/
  confetti: ^0.7.0
  fade_out_particle: ^1.2.1
  google_fonts: ^6.1.0
  animated_flip_counter: ^0.2.6
  flutter_riverpod: ^2.4.10
  simple_animations: ^5.0.2
  sprite: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/recycling.png
    - assets/trash_sprite/
