name: envawareness
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.3.0+5

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  animated_text_kit: ^4.2.2
  image_picker: ^1.0.7
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2

  go_router: ^13.2.0

  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.1
  flutter_tilt: ^2.4.0
  google_sign_in: ^6.2.1
  sensors_plus: ^4.0.2
  zflutter:
    git:
      url: https://github.com/CarGuo/zflutter.git
      ref: 3f5e569ba96f4c94a5847aad96617f273d88629d
      path: zflutter/
  confetti: ^0.7.0
  fade_out_particle: ^1.2.1
  google_fonts: ^6.2.1
  animated_flip_counter: ^0.2.6
  simple_animations: ^5.0.2
  lottie: ^3.1.0
  sprite: ^0.0.3
  appinio_swiper: ^2.1.0
  flutter_animate: ^4.5.0
  audioplayers: ^5.2.1

  url_launcher: ^6.2.5
  google_generative_ai: ^0.2.2
  uuid: ^4.3.3
  add_to_google_wallet: ^0.0.3
  app_settings: ^5.1.1

  # For Web
  universal_io: ^2.2.2

dependency_overrides:
  web: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_launcher_icons: '^0.13.1'

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/trash_sprite/
    - assets/images/recycle/
    - assets/images/game/
    - assets/sounds/
    - assets/animations/
