const recycleData = [
  {
    'name': '紙餐盒加蓋',
    'name_en': 'Paper food container with lid',
    'name_jp': '紙弁当箱（蓋付き）',
    'image_url': 'assets/images/recycle/paper_food_container_with_lid.webp',
    'value': 2,
  },
  {
    'name': '塑膠飲料底座/ 杯架',
    'name_en': 'Plastic drink base/cup holder',
    'name_jp': 'ドリンクホルダー（プラスチック）',
    'image_url': 'assets/images/recycle/plastic_drink_base_cup_holder.webp',
    'value': 2,
  },
  {
    'name': '速食紙餐盒',
    'name_en': 'Fast food paper container',
    'name_jp': 'ファーストフード紙容器',
    'image_url': 'assets/images/recycle/fast_food_paper_container.webp',
    'value': 2,
  },
  {
    'name': '透明塑膠袋',
    'name_en': 'Clear plastic bag',
    'name_jp': '透明プラ袋',
    'image_url': 'assets/images/recycle/clear_plastic_bag.webp',
    'value': 2,
  },
  {
    'name': '塑膠飲料杯',
    'name_en': 'Plastic drink cup',
    'name_jp': 'プラスチックカップ',
    'image_url': 'assets/images/recycle/plastic_drink_cup.webp',
    'value': 2,
  },
  {
    'name': '紙飲料杯',
    'name_en': 'Paper drink cup',
    'name_jp': '紙カップ',
    'image_url': 'assets/images/recycle/paper_drink_cup.webp',
    'value': 2,
  },
  {
    'name': '紙便當盒',
    'name_en': 'Paper lunch box',
    'name_jp': '紙弁当箱',
    'image_url': 'assets/images/recycle/paper_lunch_box.webp',
    'value': 2,
  },
  {
    'name': '披薩盒',
    'name_en': 'Pizza box',
    'name_jp': 'ピザ箱',
    'image_url': 'assets/images/recycle/pizza_box.webp',
    'value': 2,
  },
  {
    'name': '手提紙袋',
    'name_en': 'Paper carry bag',
    'name_jp': '紙手提げ袋',
    'image_url': 'assets/images/recycle/paper_carry_bag.webp',
    'value': 2,
  },
  {
    'name': '沐浴乳瓶罐',
    'name_en': 'Shower gel bottle',
    'name_jp': 'シャワージェル容器',
    'image_url': 'assets/images/recycle/shower_gel_bottle.webp',
    'value': 2,
  },
  {
    'name': '生廚餘',
    'name_en': 'Raw kitchen waste',
    'name_jp': '生キッチン廃棄物',
    'image_url': 'assets/images/recycle/raw_kitchen_waste.webp',
    'value': 2,
  },
  {
    'name': '熟廚餘',
    'name_en': 'Cooked kitchen waste',
    'name_jp': '熟キッチン廃棄物',
    'value': 2,
  },
  {
    'name': '菸盒',
    'name_en': 'Cigarette box',
    'name_jp': 'タバコ箱',
    'image_url': 'assets/images/recycle/cigarette_box.webp',
    'value': 2,
  },
  {
    'name': '牛奶盒',
    'name_en': 'Milk carton',
    'name_jp': '牛乳パック',
    'image_url': 'assets/images/recycle/milk_carton.webp',
    'value': 2,
  },
  {
    'name': '優格杯',
    'name_en': 'Yogurt cup',
    'name_jp': 'ヨーグルトカップ',
    'image_url': 'assets/images/recycle/yogurt_cup.webp',
    'value': 2,
  },
  {
    'name': '枯枝落葉',
    'name_en': 'Dead branches and fallen leaves',
    'name_jp': '枯葉',
    'image_url': 'assets/images/recycle/dead_branches_and_fallen_leaves.webp',
    'value': 2,
  },
  {
    'name': '報紙',
    'name_en': 'Newspaper',
    'name_jp': '新聞',
    'image_url': 'assets/images/recycle/newspaper.webp',
    'value': 2,
  },
  {
    'name': '泡麵碗',
    'name_en': 'Instant noodle bowl',
    'name_jp': 'インスタント麺容器',
    'image_url': 'assets/images/recycle/instant_noodle_bowl.webp',
    'value': 2,
  },
  {
    'name': '玻璃瓶',
    'name_en': 'Glass bottle',
    'name_jp': 'ガラス瓶',
    'image_url': 'assets/images/recycle/glass_bottle.webp',
    'value': 2,
  },
  {
    'name': '衛生紙包裝',
    'name_en': 'Toilet paper packaging',
    'image_url': 'assets/images/recycle/toilet_paper_packaging.webp',
    'name_jp': 'トイペ包装',
    'value': 2,
  },
  {
    'name': '奶粉罐',
    'name_en': 'Powdered milk can',
    'name_jp': '粉ミルク缶',
    'image_url': 'assets/images/recycle/powdered_milk_can.webp',
    'value': 2,
  },
  {
    'name': '網購紙箱',
    'name_en': 'Online shopping cardboard box',
    'name_jp': 'ダンボール箱',
    'image_url': 'assets/images/recycle/online_shopping_cardboard_box.webp',
    'value': 2,
  },
  {
    'name': '光碟',
    'name_en': 'CD/DVD',
    'name_jp': 'CD/DVD',
    'image_url': 'assets/images/recycle/cd_dvd.webp',
    'value': 2,
  },
  {
    'name': '鋁箔包',
    'name_en': 'Aluminum foil pack',
    'name_jp': 'アルミパック',
    'image_url': 'assets/images/recycle/aluminum_foil_pack.webp',
    'value': 2,
  },
  {
    'name': '鋁罐',
    'name_en': 'Aluminum can',
    'name_jp': 'アルミ缶',
    'image_url': 'assets/images/recycle/aluminum_can.webp',
    'value': 2,
  },
  {
    'name': '油漆桶',
    'name_en': 'Paint can',
    'name_jp': '塗料缶',
    'image_url': 'assets/images/recycle/paint_can.webp',
    'value': 2,
  },
  {
    'name': '寶特瓶',
    'name_en': 'PET bottle',
    'name_jp': 'ペットボトル',
    'image_url': 'assets/images/recycle/pet_bottle.webp',
    'value': 2,
  },
  {
    'name': '帳單信封',
    'name_en': 'Billing envelope',
    'name_jp': '請求書封筒',
    'image_url': 'assets/images/recycle/billing_envelope.webp',
    'value': 2,
  },
  {
    'name': '高壓瓶',
    'name_en': 'High-pressure bottle',
    'name_jp': '高圧ボトル',
    'image_url': 'assets/images/recycle/high_pressure_bottle.webp',
    'value': 2,
  },
  {
    'name': '餅乾禮盒',
    'name_en': 'Cookie gift box',
    'name_jp': 'クッキー箱',
    'image_url': 'assets/images/recycle/cookie_gift_box.webp',
    'value': 2,
  },
  {
    'name': '鋁製膠囊咖啡',
    'name_en': 'Aluminum capsule coffee',
    'name_jp': 'カプセルコーヒー',
    'image_url': 'assets/images/recycle/aluminum_capsule_coffee.webp',
    'value': 1,
  },
  {
    'name': '鋁箔餐盒',
    'name_en': 'Aluminum foil food container',
    'name_jp': 'アルミ容器',
    'image_url': 'assets/images/recycle/aluminum_foil_food_container.webp',
    'value': 1,
  },
  {
    'name': '安全帽',
    'name_en': 'Safety helmet',
    'name_jp': '安全ヘルメット',
    'image_url': 'assets/images/recycle/safety_helmet.webp',
    'value': 1,
  },
  {
    'name': '罐裝洋芋片',
    'name_en': 'Canned potato chips',
    'name_jp': 'ポテチ缶',
    'image_url': 'assets/images/recycle/canned_potato_chips.webp',
    'value': 1,
  },
  {
    'name': '輕便雨衣',
    'name_en': 'Disposable raincoat',
    'name_jp': '使い捨てレインコート',
    'image_url': 'assets/images/recycle/disposable_raincoat.webp',
    'value': 1,
  },
  {
    'name': '塑膠湯匙',
    'name_en': 'Plastic spoon',
    'name_jp': 'プラスチックスプーン',
    'image_url': 'assets/images/recycle/plastic_spoon.webp',
    'value': 1,
  },
  {
    'name': '透明雞蛋盒',
    'name_en': 'Clear egg carton',
    'name_jp': '卵箱',
    'image_url': 'assets/images/recycle/clear_egg_carton.webp',
    'value': 1,
  },
  {
    'name': '原子筆',
    'name_en': 'Ballpoint pen',
    'name_jp': 'ボールペン',
    'image_url': 'assets/images/recycle/ballpoint_pen.webp',
    'value': 1,
  },
  {
    'name': '洗面乳',
    'name_en': 'Facial cleanser',
    'name_jp': '洗顔乳',
    'image_url': 'assets/images/recycle/facial_cleanser.webp',
    'value': 1,
  },
  {
    'name': '洋蔥網袋',
    'name_en': 'Onion net bag',
    'name_jp': '玉ねぎネット',
    'image_url': 'assets/images/recycle/onion_net_bag.webp',
    'value': 1,
  },
  {
    'name': '充電線',
    'name_en': 'Charging cable',
    'name_jp': '充電ケーブル',
    'image_url': 'assets/images/recycle/charging_cable.webp',
    'value': 1,
  },
  {
    'name': '養樂多',
    'name_en': 'Yakult',
    'name_jp': 'ヤクルト',
    'value': 1,
  },
  {
    'name': '木製品',
    'name_en': 'Wooden items',
    'name_jp': '木製品',
    'image_url': 'assets/images/recycle/wooden_items.webp',
    'value': 1,
  },
  {
    'name': '塑膠餐盒',
    'name_en': 'Plastic meal box',
    'name_jp': 'プラ食品容器',
    'image_url': 'assets/images/recycle/plastic_meal_box.webp',
    'value': 1,
  },
  {
    'name': '瑜珈墊',
    'name_en': 'Yoga mat',
    'name_jp': 'ヨガマット',
    'image_url': 'assets/images/recycle/yoga_mat.webp',
    'value': 1,
  },
  {
    'name': '水果網套',
    'name_en': 'Fruit net bag',
    'name_jp': '果物ネット',
    'image_url': 'assets/images/recycle/fruit_net_bag.webp',
    'value': 1,
  },
  {
    'name': '免洗筷',
    'name_en': 'Disposable chopsticks',
    'name_jp': '使い捨て箸',
    'image_url': 'assets/images/recycle/disposable_chopsticks.webp',
    'value': 1,
  },
  {
    'name': '耳機',
    'name_en': 'Earphones',
    'name_jp': 'イヤホン',
    'image_url': 'assets/images/recycle/earphones.webp',
    'value': 1,
  },
  {
    'name': '泡泡紙',
    'name_en': 'Bubble wrap',
    'name_jp': 'バブルラップ',
    'image_url': 'assets/images/recycle/bubble_wrap.webp',
    'value': 1,
  },
  {
    'name': '碎紙',
    'name_en': 'Shredded paper',
    'image_url': 'assets/images/recycle/shredded_paper.webp',
    'name_jp': '細断紙',
    'value': 1,
  },
  {
    'name': '衣架',
    'name_en': 'Clothes hanger',
    'name_jp': 'ハンガー',
    'image_url': 'assets/images/recycle/clothes_hanger.webp',
    'value': 1,
  },
  {
    'name': '塑膠吸管',
    'name_en': 'Plastic straw',
    'name_jp': 'ストロー',
    'image_url': 'assets/images/recycle/plastic_straw.webp',
    'value': 1,
  },
  {
    'name': '釘書針',
    'name_en': 'Staple',
    'name_jp': 'ステープル',
    'image_url': 'assets/images/recycle/staple.webp',
    'value': 1,
  },
  {
    'name': '拖把',
    'name_en': 'Mop',
    'name_jp': 'モップ',
    'image_url': 'assets/images/recycle/mop.webp',
    'value': 1,
  },
  {
    'name': '旅行行李箱',
    'name_en': 'Travel suitcase',
    'name_jp': 'スーツケース',
    'image_url': 'assets/images/recycle/travel_suitcase.webp',
    'value': 1,
  },
  {
    'name': '牙膏',
    'name_en': 'Toothpaste',
    'name_jp': '歯磨き粉',
    'image_url': 'assets/images/recycle/toothpaste.webp',
    'value': 1,
  },
  {
    'name': '彩色筆',
    'name_en': 'Colored pens',
    'name_jp': 'カラーペン',
    'image_url': 'assets/images/recycle/colored_pens.webp',
    'value': 1,
  },
  {
    'name': '滑鼠',
    'name_en': 'Mouse (computer accessory)',
    'name_jp': 'マウス',
    'image_url': 'assets/images/recycle/mouse_computer_accessory.webp',
    'value': 1,
  },
  {
    'name': '夾腳拖',
    'name_en': 'Flip-flops',
    'name_jp': 'ビーチサンダル',
    'image_url': 'assets/images/recycle/flip_flops.webp',
    'value': 1,
  },
  {
    'name': '雨傘',
    'name_en': 'Umbrella',
    'name_jp': '傘',
    'image_url': 'assets/images/recycle/umbrella.webp',
    'value': 1,
  },
  {
    'name': '生鮮托盤',
    'name_en': 'Fresh produce tray',
    'name_jp': 'トレイ',
    'image_url': 'assets/images/recycle/fresh_produce_tray.webp',
    'value': 1,
  },
  {
    'name': '保養品瓶罐',
    'name_en': 'Cosmetic bottles and jars',
    'name_jp': '化粧品容器',
    'image_url': 'assets/images/recycle/cosmetic_bottles_and_jars.webp',
    'value': 1,
  },
  {
    'name': '塑膠醬料盒',
    'name_en': 'Plastic sauce container',
    'name_jp': 'ソース容器',
    'image_url': 'assets/images/recycle/plastic_sauce_container.webp',
    'value': 0,
  },
  {
    'name': '植物纖維餐盒',
    'name_en': 'Plant fiber food container',
    'name_jp': '植物容器',
    'image_url': 'assets/images/recycle/plant_fiber_food_container.webp',
    'value': 0,
  },
  {
    'name': '木片餐盒',
    'name_en': 'Wooden food container',
    'name_jp': '木容器',
    'image_url': 'assets/images/recycle/wooden_food_container.webp',
    'value': 0,
  },
  {
    'name': '漢堡紙/ 三明治紙',
    'name_en': 'Burger/sandwich paper',
    'name_jp': 'ハンバーガー紙',
    'image_url': 'assets/images/recycle/burger_sandwich_paper.webp',
    'value': 0,
  },
  {
    'name': '蔬菜塑膠袋',
    'name_en': 'Vegetable plastic bag',
    'name_jp': '野菜袋',
    'image_url': 'assets/images/recycle/vegetable_plastic_bag.webp',
    'value': 0,
  },
  {
    'name': '髒髒塑膠袋',
    'name_en': 'Dirty plastic bag',
    'name_jp': '汚れたプラ袋',
    'image_url': 'assets/images/recycle/dirty_plastic_bag.webp',
    'value': 0,
  },
  {
    'name': '電子發票',
    'name_en': 'Electronic receipt',
    'name_jp': '電子レシート',
    'image_url': 'assets/images/recycle/electronic_receipt.webp',
    'value': 0,
  },
  {
    'name': '袋裝洋芋片',
    'name_en': 'Bagged potato chips',
    'name_jp': 'ポテチ袋',
    'image_url': 'assets/images/recycle/bagged_potato_chips.webp',
    'value': 0,
  },
  {
    'name': '橡皮筋',
    'name_en': 'Rubber band',
    'name_jp': 'ゴムバンド',
    'image_url': 'assets/images/recycle/rubber_band.webp',
    'value': 0,
  },
  {
    'name': '瓷器',
    'name_en': 'Porcelain',
    'name_jp': '陶器',
    'image_url': 'assets/images/recycle/porcelain.webp',
    'value': 0,
  },
  {
    'name': '醫療口罩',
    'name_en': 'Surgical mask',
    'name_jp': 'マスク',
    'image_url': 'assets/images/recycle/surgical_mask.webp',
    'value': 0,
  },
  {
    'name': '絨毛玩偶',
    'name_en': 'Plush toy',
    'name_jp': 'ぬいぐるみ',
    'image_url': 'assets/images/recycle/plush_toy.webp',
    'value': 0,
  },
  {
    'name': '產品外包裝',
    'name_en': 'Product packaging',
    'name_jp': '外装',
    'image_url': 'assets/images/recycle/product_packaging.webp',
    'value': 0,
  },
  {
    'name': '盆栽',
    'name_en': 'Potted plant',
    'name_jp': '鉢植え',
    'image_url': 'assets/images/recycle/potted_plant.webp',
    'value': 0,
  },
  {
    'name': '薄塑膠盒',
    'name_en': 'Thin plastic box',
    'name_jp': 'プラ容器',
    'value': 0,
  },
  {
    'name': '奶油球',
    'name_en': 'Cream charger',
    'name_jp': 'クリームチャージャー',
    'value': 0,
  },
  {
    'name': '馬桶刷',
    'name_en': 'Toilet brush',
    'name_jp': 'トイレブラシ',
    'value': 0,
  },
  {
    'name': '紙尿布',
    'name_en': 'Diaper',
    'name_jp': '紙おむつ',
    'value': 0,
  },
  {
    'name': '濾水器濾芯',
    'name_en': 'Water filter cartridge',
    'name_jp': 'フィルター',
    'value': 0,
  },
  {
    'name': '手機殼',
    'name_en': 'Phone case',
    'name_jp': 'スマホケース',
    'value': 0,
  },
  {
    'name': '鏡子',
    'name_en': 'Mirror',
    'name_jp': '鏡',
    'value': 0,
  },
  {
    'name': '口紅',
    'name_en': 'Lipstick',
    'name_jp': '口紅',
    'value': 0,
  },
  {
    'name': '鉛筆',
    'name_en': 'Pencil',
    'name_jp': '鉛筆',
    'value': 0,
  },
  {
    'name': '補充包',
    'name_en': 'Refill pack',
    'name_jp': '詰め替えパック',
    'value': 0,
  },
  {
    'name': '小吃紙袋',
    'name_en': 'Snack paper bag',
    'name_jp': 'スナック袋',
    'value': 0,
  },
  {
    'name': '鋁箔紙',
    'name_en': 'Aluminum foil paper',
    'name_jp': 'アルミホイル',
    'value': 0,
  },
  {
    'name': '棉被枕頭',
    'name_en': 'Quilt and pillow',
    'name_jp': '寝具',
    'value': 0,
  },
  {
    'name': '廢棄藥品',
    'name_en': 'Expired medicine',
    'name_jp': '廃薬',
    'value': 0,
  },
  {
    'name': '立可帶',
    'name_en': 'Lickable strip (e.g., for envelopes)',
    'name_jp': '立てるテープ',
    'value': 0,
  },
  {
    'name': '玩具',
    'name_en': 'Toy',
    'name_jp': 'おもちゃ',
    'value': 0,
  },
  {
    'name': '膠囊咖啡',
    'name_en': 'Capsule coffee',
    'name_jp': 'カプセルコーヒー',
    'value': 0,
  },
  {
    'name': '棉花棒',
    'name_en': 'Cotton swab',
    'name_jp': '綿棒',
    'value': 0,
  },
  {
    'name': '打火機',
    'name_en': 'Lighter',
    'name_jp': 'ライター',
    'value': 0,
  },
  {
    'name': '碎玻璃',
    'name_en': 'Broken glass',
    'name_jp': 'ガラスくず',
    'value': 0,
  },
  {
    'name': '隱形眼鏡',
    'name_en': 'Contact lens',
    'name_jp': 'コンタクト',
    'value': 0,
  },
  {
    'name': '不織布提袋',
    'name_en': 'Non-woven tote bag',
    'name_jp': '不織布バッグ',
    'value': 0,
  },
  {
    'name': '信用卡',
    'name_en': 'Credit card',
    'name_jp': 'クレジットカード',
    'value': 0,
  },
  {
    'name': '塑膠牙線棒',
    'name_en': 'Plastic dental floss pick',
    'name_jp': 'デンタルフロス',
    'value': 0,
  },
  {
    'name': '保鮮膜',
    'name_en': 'Cling film',
    'name_jp': 'ラップ',
    'value': 0,
  },
  {
    'name': '牙刷',
    'name_en': 'Toothbrush',
    'name_jp': '歯ブラシ',
    'value': 0,
  },
  {
    'name': '衣物',
    'name_en': 'Clothing',
    'name_jp': '衣類',
    'value': 0,
  },
  {
    'name': '環保袋',
    'name_en': 'Eco-friendly bag',
    'name_jp': 'エコバッグ',
    'value': 0,
  },
  {
    'name': '鞋',
    'name_en': 'Shoes',
    'name_jp': '靴',
    'value': 0,
  },
];
